CREATE TABLE TEACHER (
id INTEGER NOT NULL AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
age NUMBERIC (3) NOT NULL, -- NUMBERIC(3) means INTEGER
nationality VARCHAR(2) NOT NULL,
membership VARCHAR(1) NOT NULL

);