import java.util.Arrays;

public class leetcode389 {

  // You are given two strings s and t.

  // String t is generated by random shuffling string s and then add one more letter at a random position.
  
  // Return the letter that was added to t.
  
  
  // Example 1:
  
  // Input: s = "abcd", t = "abcde"
  // Output: "e"
  // Explanation: 'e' is the letter that was added.

  // Example 2:
  
  // Input: s = "", t = "y"
  // Output: "y"
   
  
  // Constraints:
  
  // 0 <= s.length <= 1000
  // t.length == s.length + 1
  // s and t consist of lowercase English letters.


  public static char findTheDifference(String s, String t) {
        
      int[] count = new int[26];
      for (char c : s.toCharArray()) {
          count[c - 'a']++;
          System.out.println("count[c - 'a'] count ++ =" + count[c - 'a']);
          System.out.println(Arrays.toString(count));

      }
      for (char c : t.toCharArray()) {
          count[c - 'a']--;
          System.out.println("count[c - 'a'] count -- =" + count[c - 'a']);
          System.out.println(Arrays.toString(count));
      }
      for (int i = 0; i < count.length; i++) {
          if (count[i] != 0) {
              return (char) (i + 'a');
          }
      }
      throw new IllegalArgumentException("Invalid input"); // <-- if input is null, then will error
      //array同String會常用既
  }
      

public static void main(String [] args){

  System.out.println(findTheDifference("abcd", "abcde"));



}



}
